image:
  - ubuntu

platform:
  - x64

services:
  - docker
  
branches:
  except:
    - /.*/

build_script:
  - docker pull quay.io/puteulanus/zsun-builder
  - docker tag quay.io/puteulanus/zsun-builder build
  - mkdir build_dir
  - docker run -v `pwd`/build_dir:/mnt/build_dir build cp -r /root/openwrt /mnt/build_dir/zsun
  - cp build_dir/zsun/targets/ar71xx/generic/lede-ar71xx-generic-zsun-sdreader-squashfs-sysupgrade.bin ./
  - cp build_dir/zsun/targets/ar71xx/generic/*.tar.xz ./
  - md5sum build_dir/zsun/targets/ar71xx/generic/*sysupgrade.bin > lede-md5.txt
  - sha256sum build_dir/zsun/targets/ar71xx/generic/*sysupgrade.bin > lede-sha256.txt
  - docker pull quay.io/puteulanus/zsun-builder:18.06_rec
  - docker tag quay.io/puteulanus/zsun-builder:18.06_rec build-3
  - mkdir build_dir-3
  - docker run -v `pwd`/build_dir-3:/mnt/build_dir build-3 cp -r /root/openwrt /mnt/build_dir/zsun
  - cp build_dir-3/zsun/targets/ar71xx/generic/openwrt-ar71xx-generic-zsun-sdreader-squashfs-sysupgrade.bin ./openwrt_rec-ar71xx-generic-zsun-sdreader-squashfs-sysupgrade.bin
  - cp build_dir-3/zsun/targets/ar71xx/generic/openwrt-imagebuilder*.tar.xz ./openwrt_rec-imagebuilder.tar.xz
  - cp build_dir-3/zsun/targets/ar71xx/generic/openwrt-sdk*.tar.xz ./openwrt_rec-sdk.tar.xz
  - md5sum build_dir-3/zsun/targets/ar71xx/generic/*sysupgrade.bin > openwrt_rec-md5.txt
  - sha256sum build_dir-3/zsun/targets/ar71xx/generic/*sysupgrade.bin > openwrt_rec-sha256.txt
  - rm -rf config.txt

artifacts:
  - path: 'openwrt-ar71xx-generic-zsun-sdreader-squashfs-sysupgrade.bin'
    name: openwrt-firmware
    
  - path: 'openwrt_rec-ar71xx-generic-zsun-sdreader-squashfs-sysupgrade.bin'
    name: openwrt_rec-firmware
    
  - path: 'lede*.bin'
    name: lede-firmware
  
  - path: '*.tar.xz'
    name: builder
    
  - path: '*.txt'
    name: hash
